services:
  front:
    container_name: front-react
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - './front:/app'
      - './front/node_modules:/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  back:
    container_name: back-nest
    build:
      context: ./back
      dockerfile: Dockerfile
    restart: always
    env_file: ./back/.env
    volumes:
      - ./back:/svr/app
      - /svr/app/node_modules
    networks:
      - twitter-network
    ports:
      - "${NEST_PORT}:${NEST_PORT}"

networks:
  twitter-network:
    driver: bridge